In [1]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import pickle

In [2]:
df = pd.read_csv('UpdatedResumeDataSet.csv')
df

Category                                             Resume
0    Data Science  Skills * Programming Languages: Python (pandas...
1    Data Science  Education Details \r\nMay 2013 to May 2017 B.E...
2    Data Science  Areas of Interest Deep Learning, Control Syste...
3    Data Science  Skills • R • Python • SAP HANA • Table...
4    Data Science  Education Details \r\n MCA   YMCAUST,  Faridab...
..            ...                                                ...
957       Testing  Computer Skills: • Proficient in MS office (...
958       Testing  ❖ Willingness to accept the challenges. ❖ ...
959       Testing  PERSONAL SKILLS • Quick learner, • Eagerne...
960       Testing  COMPUTER SKILLS & SOFTWARE KNOWLEDGE MS-Power ...
961       Testing  Skill Set OS Windows XP/7/8/8.1/10 Database MY...

[962 rows x 2 columns]

In [3]:
for i in range(len(df['Category'].unique())):
    print(df['Category'].unique()[i])

Data Science
HR
Advocate
Arts
Web Designing
Mechanical Engineer
Sales
Health and fitness
Civil Engineer
Java Developer
Business Analyst
SAP Developer
Automation Testing
Electrical Engineering
Operations Manager
Python Developer
DevOps Engineer
Network Security Engineer
PMO
Database
Hadoop
ETL Developer
DotNet Developer
Blockchain
Testing


In [4]:
print(df.isnull().sum())

Category    0
Resume      0
dtype: int64


In [5]:
df['Resume'] = df['Resume'].apply(lambda x:x.lower())
for i in range(len(df)):
    lw=[]
    for j in df['Resume'][i].split():
        if len(j)>3:                  
            lw.append(j)
    df['Resume'][i]=" ".join(lw)

In [6]:
df.Resume

0      skills programming languages: python (pandas, ...
1      education details 2013 2017 uit-rgpv data scie...
2      areas interest deep learning, control system d...
3      skills python hana tableau hana hana lumira li...
4      education details ymcaust, faridabad, haryana ...
                             ...                        
957    computer skills: proficient office (word, basi...
958    willingness accept challenges. positive thinki...
959    personal skills quick learner, eagerness learn...
960    computer skills software knowledge ms-power po...
961    skill windows xp/7/8/8.1/10 database mysql, se...
Name: Resume, Length: 962, dtype: object

In [7]:
ps = list(";?.:!,")
df['Resume'] = df['Resume']

for p in ps:   
    df['Resume'] = df['Resume'].str.replace(p, '')

C:\Users\Sangram\AppData\Local\Temp\ipykernel_20884\2980719137.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Resume'] = df['Resume'].str.replace(p, '')


In [8]:
df.Resume

0      skills programming languages python (pandas nu...
1      education details 2013 2017 uit-rgpv data scie...
2      areas interest deep learning control system de...
3      skills python hana tableau hana hana lumira li...
4      education details ymcaust faridabad haryana da...
                             ...                        
957    computer skills proficient office (word basic ...
958    willingness accept challenges positive thinkin...
959    personal skills quick learner eagerness learn ...
960    computer skills software knowledge ms-power po...
961    skill windows xp/7/8/81/10 database mysql serv...
Name: Resume, Length: 962, dtype: object

In [9]:
df['Resume'] = df['Resume'].str.replace("    ", " ")
df['Resume'] = df['Resume'].str.replace('"', '')
df['Resume'] = df['Resume'].apply(lambda x: x.replace('\t', ' '))
df['Resume'] = df['Resume'].str.replace("'s", "")
df['Resume'] = df['Resume'].apply(lambda x: x.replace('\n', ' '))

In [10]:
df.Resume

0      skills programming languages python (pandas nu...
1      education details 2013 2017 uit-rgpv data scie...
2      areas interest deep learning control system de...
3      skills python hana tableau hana hana lumira li...
4      education details ymcaust faridabad haryana da...
                             ...                        
957    computer skills proficient office (word basic ...
958    willingness accept challenges positive thinkin...
959    personal skills quick learner eagerness learn ...
960    computer skills software knowledge ms-power po...
961    skill windows xp/7/8/81/10 database mysql serv...
Name: Resume, Length: 962, dtype: object

In [11]:
pip install nltk

Note: you may need to restart the kernel to use updated packages.


In [12]:
import nltk

In [13]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [14]:
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Sangram\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Sangram\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Sangram\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [15]:
wl = WordNetLemmatizer()
nr = len(df)
lis = []
for r in range(0, nr):
    ll = []
    t = df.loc[r]['Resume']
    tw = str(t).split(" ")
    for w in tw:
        ll.append(wl.lemmatize(w, pos="v"))
    lt = " ".join(ll)
    lis.append(lt)

In [16]:
df['Resume'] = lis

In [17]:
df.Resume

0      skills program languages python (pandas numpy ...
1      education detail 2013 2017 uit-rgpv data scien...
2      areas interest deep learn control system desig...
3      skills python hana tableau hana hana lumira li...
4      education detail ymcaust faridabad haryana dat...
                             ...                        
957    computer skills proficient office (word basic ...
958    willingness accept challenge positive think go...
959    personal skills quick learner eagerness learn ...
960    computer skills software knowledge ms-power po...
961    skill windows xp/7/8/81/10 database mysql serv...
Name: Resume, Length: 962, dtype: object

In [18]:
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer
le = LabelEncoder()
df['Category'] = le.fit_transform(df['Category'])
cv = CountVectorizer(max_features = 2500)
cv.fit(df['Resume'])
X = cv.transform(df['Resume']).toarray()
y = df['Category']

In [19]:
print(X)
print(y)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]
0       6
1       6
2       6
3       6
4       6
       ..
957    23
958    23
959    23
960    23
961    23
Name: Category, Length: 962, dtype: int32


In [20]:
# from sklearn.preprocessing import LabelEncoder
# from sklearn.feature_extraction.text import CountVectorizer

# # Assume the encoded data is in the variable 'encoded_data'
# decoded_data = LabelEncoder().fit_transform(X)

# # Now you can decode the data
# original_data = LabelEncoder().inverse_transform(decoded_data)

# df['Category'] = original_data

# cv = CountVectorizer(max_features=2500)
# X = cv.fit_transform(df['Resume']).toarray()
# y = df['Category']

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, stratify=y, random_state = 42)

In [22]:
from sklearn import tree
from sklearn.metrics import accuracy_score

In [23]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
yp = clf.predict(X_test)
acc = accuracy_score(y_test, yp)
print("accuracy is: ",acc)
print(yp)
print(df['Category'])

accuracy is:  0.9826989619377162
[20  4 14 24  8 16  4 19  7  7  6 21  4  7  8 24 15 12  9 14 17  0 22  5
 14 10  5  1  2  3  1  7 14 12 12 13 20 15 10 23 12  4 22 10 13 22 16 13
  7  3  3 22  8 19  7 11 15 21  8 24 10  8  2 19 23 13  3 12 11 22 24 16
  3  3 15  6  6 24 10 15  7  9  4  5 19 13 17 23 24  6  2 15 18  1 13  8
 23 23 11  1 16 15  0 23 21 24 12 23 20 11 22 23 10 13 15  6 14 21 15 17
 14 11 16 15 19 13  7 20 15 12  6 10  5 22 10 23  8 15 10 22  8 15  0  9
 22  8  6  8 20 12  8 18  4 16 15 13 10 23  4  1 22 21 10  8 15 20 20 15
 18 13 18  2 22 11  6 15 19  1 23 20 24 14 18  5 14 17 12 23 23 16 15 23
 18 20  5 21 24 23  1  6  9 13 15 24  7 21 19  2 24  2  2  6 15 16 15 23
 15 12 23  0 12 17 16 14  0 21 16 10 18  5  2 19 21 16 12  8 17  3 18 23
  8 18 23 12  3 11  8 15 23 11  1  4 24 13 21 18  0 20  3  6  8 13  3  3
  1 20 22 15 18 15 24 23 18 11  2 17  1  1 16 19 21 17 24  3 20  6 20 20
  7]
0       6
1       6
2       6
3       6
4       6
       ..
957    23
958    23
959   

In [24]:
yp = clf.predict(X_test)
print("Predicted output: ", yp)

Predicted output:  [20  4 14 24  8 16  4 19  7  7  6 21  4  7  8 24 15 12  9 14 17  0 22  5
 14 10  5  1  2  3  1  7 14 12 12 13 20 15 10 23 12  4 22 10 13 22 16 13
  7  3  3 22  8 19  7 11 15 21  8 24 10  8  2 19 23 13  3 12 11 22 24 16
  3  3 15  6  6 24 10 15  7  9  4  5 19 13 17 23 24  6  2 15 18  1 13  8
 23 23 11  1 16 15  0 23 21 24 12 23 20 11 22 23 10 13 15  6 14 21 15 17
 14 11 16 15 19 13  7 20 15 12  6 10  5 22 10 23  8 15 10 22  8 15  0  9
 22  8  6  8 20 12  8 18  4 16 15 13 10 23  4  1 22 21 10  8 15 20 20 15
 18 13 18  2 22 11  6 15 19  1 23 20 24 14 18  5 14 17 12 23 23 16 15 23
 18 20  5 21 24 23  1  6  9 13 15 24  7 21 19  2 24  2  2  6 15 16 15 23
 15 12 23  0 12 17 16 14  0 21 16 10 18  5  2 19 21 16 12  8 17  3 18 23
  8 18 23 12  3 11  8 15 23 11  1  4 24 13 21 18  0 20  3  6  8 13  3  3
  1 20 22 15 18 15 24 23 18 11  2 17  1  1 16 19 21 17 24  3 20  6 20 20
  7]


In [25]:
# le = LabelEncoder()
# le.fit(df['Category'])
y_pred_decoded = le.inverse_transform(yp)

print("Predicted labels: ", y_pred_decoded)

Predicted labels:  ['Python Developer' 'Business Analyst' 'Health and fitness'
 'Web Designing' 'DevOps Engineer' 'Mechanical Engineer'
 'Business Analyst' 'PMO' 'Database' 'Database' 'Data Science'
 'SAP Developer' 'Business Analyst' 'Database' 'DevOps Engineer'
 'Web Designing' 'Java Developer' 'HR' 'DotNet Developer'
 'Health and fitness' 'Network Security Engineer' 'Advocate' 'Sales'
 'Civil Engineer' 'Health and fitness' 'ETL Developer' 'Civil Engineer'
 'Arts' 'Automation Testing' 'Blockchain' 'Arts' 'Database'
 'Health and fitness' 'HR' 'HR' 'Hadoop' 'Python Developer'
 'Java Developer' 'ETL Developer' 'Testing' 'HR' 'Business Analyst'
 'Sales' 'ETL Developer' 'Hadoop' 'Sales' 'Mechanical Engineer' 'Hadoop'
 'Database' 'Blockchain' 'Blockchain' 'Sales' 'DevOps Engineer' 'PMO'
 'Database' 'Electrical Engineering' 'Java Developer' 'SAP Developer'
 'DevOps Engineer' 'Web Designing' 'ETL Developer' 'DevOps Engineer'
 'Automation Testing' 'PMO' 'Testing' 'Hadoop' 'Blockchain' 'HR'
 '

In [26]:
pickle.dump(clf,open('clf.pkl','wb'))
pickle.dump(le,open('le.pkl','wb'))
pickle.dump(cv,open('cv.pkl','wb'))

In [27]:
loaded_model = pickle.load(open('clf.pkl','rb'))
loaded_le = pickle.load(open('le.pkl','rb'))
loaded_cv = pickle.load(open('cv.pkl','rb'))

In [36]:
str = 50*" I am a Java Developer "
c = loaded_cv.transform([str])
print(c)

  (0, 652)	50
  (0, 1198)	50


In [37]:
var = loaded_model.predict(c)

In [38]:
loaded_le.inverse_transform(var)

array(['Java Developer'], dtype=object)